name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 13 22 * * *

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: script/run-in-docker.sh make test